In [2]:
1+1

2

In [3]:
2**1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [4]:
for _ in range(10):
    print(_)

0
1
2
3
4
5
6
7
8
9


In [5]:
data = [_ for _ in range(1,20)]

In [6]:
data

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [7]:
data[::3]

[1, 4, 7, 10, 13, 16, 19]

In [8]:
data[:10]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
%timeit l = 2**10000

22.2 µs ± 2.81 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
%timeit t = [i for i in range(1,1000000)]

86.2 ms ± 8.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
%time f = 2**10000

Wall time: 996 µs


In [12]:
import random
l = [random.random() for i in range(100000)]
%timeit l.sort()

1.73 ms ± 219 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [13]:
l = [random.random() for i in range(100000)]
%time l.sort()

Wall time: 22.9 ms


In [14]:
%time l.sort()

Wall time: 3.99 ms


In [15]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [16]:
import urllib
urllib.request?

In [17]:
import numpy as np

In [18]:
np.__version__

'1.17.0'

In [19]:
nparr = np.array([i for i in range(0,10)])

In [20]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
nparr.dtype

dtype('int32')

In [22]:
nparr2 = np.array([1,2,3.0])

In [23]:
nparr2.dtype

dtype('float64')

In [24]:
nparr2

array([1., 2., 3.])

In [25]:
nparr2[2] = 3.2

In [26]:
nparr2

array([1. , 2. , 3.2])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros(10).dtype

dtype('float64')

In [29]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
a = np.zeros(10,dtype=int)

In [31]:
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
a.dtype

dtype('int32')

In [33]:
b = np.zeros((3,5))

In [34]:
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
c = np.ones(10)

In [36]:
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
d = np.full((3,5),666)

In [38]:
d

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [39]:
np

<module 'numpy' from 'c:\\users\\admin\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\numpy\\__init__.py'>